name: First-Workflow
# on: workflow_dispatch
on:
  push:
    branches:
      - 'main'
jobs:  
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print GoodBye
        run: echo "First output"
