name: First-Workflow
# on: workflow_dispatch
  on: [push, workflow_dispatch]
    branches:
      - 'main'
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: build code
        run: echo "Hello World!"
      - name: create package
        run: echo "First output"
  deploy:
  # needs used to run jobs in sequential manner, once build completed
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: test code
        run: echo "Hello World!"
      - name: deploy code
        run: echo "First output"
